<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var \Aheadworks\Blog\ViewModel\Category\Details $viewModel */
$viewModel = $block->getViewModel();
// @codingStandardsIgnoreFile
$currentCategory = $viewModel->getCurrentCategory();
?>
<?php if ($viewModel->isNeedToDisplayDetails($currentCategory)): ?>
    <div class="blog-category category-details">
        <?php if ($viewModel->isNeedToDisplayImage($currentCategory)): ?>
            <div class="category-image">
                <div class="category-title">
            <?php echo $block->escapeHtml($currentCategory->getName()); ?>
            </div>
                <img src="<?= $block->escapeUrl($viewModel->getImageUrl($currentCategory)) ?>"
                     title="<?= $block->escapeHtml($currentCategory->getImageTitle()) ?>"
                     alt="<?= $block->escapeHtml($currentCategory->getImageAlt()) ?>"
                />
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>