<?php
/**
 * Copyright (c) 2021. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 * @codingStandardsIgnoreFile
 */

/** @var \Cart2Quote\Quotation\Block\Quote\Email\Items\Quote\Column $block */

?>

<td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>" align="right">
    <?php if (!$block->getItem()->getParentItem()) : ?>
        <?php echo $block->getRowTotalHtml(); ?>
        <?php echo $block->getTierRowTotalHtml(); ?>
    <?php endif; ?>
</td>
