<?php
//@codingStandardsIgnoreFile

/** @var Refill $block */

/** @var Data $pricingHelper */
$pricingHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$product = $block->getRefillProduct();
$balance = $block->getBalance();
$totalbalance = $balance->getAmount() - $balance->getLimitAmount();
$totalbalance = ((float)$totalbalance > 0)? 0 : abs($totalbalance);
?>
<?php if ($block->isAllowed()): ?>
    <div class="block creditline__account-refill">
        <div class="block-title">
            <strong><?= __('Select a Payment Method:') ?></strong>
        </div>
        <div class="block-content">
            <form action="<?= $block->getUrl('creditline/account/refill') ?>" method="post" autocomplete="off" id="form-send2friend">
                <fieldset class="fieldset info">
                    <?= $block->getBlockHtml('formkey') ?>
                    <input type="hidden" name="product" value="<?= $block->getRefillProduct()->getId() ?>" />
                    <input type="hidden" name="qty" value="1" />
                    <div class="field price">
                        <input type="radio" class="radio" name="total" value="<?=$pricingHelper->currency($totalbalance, false, false)?>" id="total" checked="">
                        <label class="label" for="price" style="width: 10rem;"><span><?=__('Total Balance') ?></span></label>
                        <?= $pricingHelper->currency($totalbalance, true, false) ?>
                    </div>
                    <div class="field riflllamount">
                        <input type="radio" class="radio" name="total" value="other" id="total">
                        <label class="label" for="riflllamount" style="width: 10rem;"><span><?=__('Other amount:') ?></span></label>
                        <input id="riflllamount" type="number" name="riflllamount" value="" style="max-width: 10rem;" />
                    </div>
                </fieldset>
                <div class="buttons-set">
                    <button type="submit" class="action primary"><?= __('Make a Payment') ?></button>
                </div>
            </form>
        </div>
    </div>
<?php endif ?>
