<?php /** * Copyright (c) 2020. Cart2Quote B.V. All rights reserved. * See COPYING.txt for license details. * @codingStandardsIgnoreFile */ /** @var Cart2Quote\Quotation\Block\Quote\Item\Renderer\DefaultRenderer $block */ ?> <?php if (!$block->isProductRemarkDisabled()) : ?> <div class="control comment"><textarea id="quote-<?php echo $block->escapeHtml($block->getQuoteItem()->getId()); ?>-description"
                  name="cart[<?php echo $block->escapeHtml($block->getQuoteItem()->getId()); ?>][description]"
                  title="Description"
                  placeholder="<?php echo $block->escapeHtml(__('Add your comments here.')) ?>"
                  class="input-text quotation-product-comment"
                  maxlength="1024" disabled
                  data-mage-init='{"productUpdater":{
                        "itemId": <?php echo $block->escapeHtml($block->getQuoteItem()->getId()); ?>,
                        "sessionProductKey": "description"
               }}'></textarea></div><?php endif;