<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Already Registered?')) ?></strong><span> Log In Now!</span>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input placeholder="Email Address*" name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input placeholder="Password*" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                    <div class="secondary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                </div>
            </fieldset>
        </form>
    </div>
    <?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_SocialLogin
 */
?>
<?php
/** @var \Amasty\SocialLogin\Block\Social $block */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$socialLogin = $objectManager->create('Amasty\SocialLogin\Block\Social');

$enabledSocials = $socialLogin->getEnabledSocials();
$socialButtonsType = $socialLogin->getButtonShapeClass();
$enabledLabels = $socialLogin->getButtonLabelState();
?>
<?php if (count($enabledSocials)): ?>
    <span class="amsl-separator">
        <span class="amsl-icon"><?= $block->escapeHtml(__('or'))?></span>
    </span>
    <div class="amsl-social-wrapper">
        <div class="amsl-social-login <?= ($enabledLabels && $socialButtonsType) ? '-labeled-buttons' : ''?>">
            <p class="amsl-error -social" data-am-js="am-social-error"></p>
            <span class="amsl-title"><?= $block->escapeHtml(__('or Login with')) ?></span>
            <span class="amsl-title -short"><?= $block->escapeHtml(__('Login with')) ?></span>
            <div class="amsl-buttons" data-amslogin="button-wrap">
                <?php foreach ($enabledSocials as $social): ?>
                    <div class="amsl-button-wrapper <?= $block->escapeHtmlAttr($socialButtonsType) ?> <?= $block->escapeHtmlAttr($enabledLabels ? 'with-label' : '') ?>">
                        <a class="amsl-button -<?= $block->escapeHtml($social['type']) ?>"
                           href="<?= $block->escapeUrl($social['url']) ?>"
                           <?= $socialLogin->isPopupEnabled() ? 'data-am-js="amsl-button"' : '' ?>
                           title="<?= $block->escapeHtml(__('Sign in with %1', $social['label'])) ?>">
                            <span class="amsl-social-icon"></span>
                            <?php if ($socialButtonsType && $enabledLabels): ?>
                                <span class="amsl-text">
                                    <?= $block->escapeHtml(__('Continue with %1', $social['label'])) ?>
                                </span>
                            <?php endif;?>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*" : {
                "Amasty_SocialLogin/js/am-social-login": {}
            }
        }
    </script>
<?php endif; ?>
</div>

