<?php
/**
 * Copyright (c) 2021. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 * @codingStandardsIgnoreFile
 */

/** @var \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Info $block */
?>

<?php if (!$block->getQuote()->getIsVirtual()) : ?>
    <div class="admin__page-section-item quote-shipping-address">
        <?php /* Shipping Address */ ?>
        <div class="admin__page-section-item-title">
            <span class="title"><?php echo $block->escapeHtml(__('Shipping Address')) ?></span>
        </div>
        <address class="admin__page-section-item-content">
            <?php echo $block->getFormattedAddress($block->getQuote()->getShippingAddress()); ?>
        </address>
        <?php echo $block->getSetDefaultShippingAddressHtml(); ?>
    </div>
<?php endif; ?>
