<?php
/**
 * Copyright (c) 2021. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 * @codingStandardsIgnoreFile
 */
?>
<?php /** @var \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Tab\File $block */ ?>

<?php $uploadedFiles = $block->getUploadedFiles(); ?>
<?php $quote = $block->getQuote() ?>
<form id="file_upload"
      method="post"
      action="<?php echo $block->getUrlAction() ?>"
      enctype="multipart/form-data">
    <?php echo $block->getBlockHtml('formkey') ?>
    <div class="admin__page-section-title">
        <strong class="title"><?php echo $block->escapeHtml(__('File Uploads')) ?></strong>
    </div>
    <input type="hidden" name="quote_id" value="<?php echo $block->escapeHtml($quote->getId()) ?>"/>
    <table class="upload-files">
        <thead>
        <tr>
            <td colspan="2">
                <label class="admin__field-label secondary">
                    <?php echo $block->escapeHtml(__('Upload new File(s)')) ?>
                </label>
            </td>
        </tr>
        </thead>
        <tbody id="file-upload">
        <tr data-mage-init='{"Cart2Quote_Quotation/quote/view/file-upload": {}}' class="select-file">
            <th>
                <label class="admin__field-label">
                    <?php echo $block->escapeHtml(__('Title')) ?>
                </label>
            </th>
            <td>
                <label class="admin__field-label">
                    <input type="text" name="title_0" class="input-text admin__control-text"/>
                </label>
            </td>
            <th class="uploaded-title">
                <label class="admin__field-label">
                    <?php echo $block->escapeHtml(__('Select File')) ?>
                </label>
            </th>
            <td class="uploaded-files">
                <label class="admin__field-label">
                    <input type="file" name="fileupload_0"/>
                </label>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="button" onclick="newUploadRow()" class="action-additional action-change-customer">
                    (+) <?php echo __('Add another file') ?>
                </button>
                <button class="action-secondary upload-file" type="submit"
                        onclick='upload("<?php echo $block->escapeHtml($block->getUrl('quotation/file/upload')) ?>");return false;'>
                    <?php echo __('Upload Files') ?>
                </button>
            </td>
        </tr>
        </tbody>
    </table>
    <table class="uploaded-files">
        <?php if (is_array($uploadedFiles)) : ?>
            <thead>
            <tr>
                <th colspan="3">
                    <label class="admin__field-label secondary" for="uploaded_files">
                        <?php echo $block->escapeHtml(__('Uploaded Files')) ?>
                    </label>
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th><?php echo $block->escapeHtml(__('Name')) ?></th>
                <th><?php echo $block->escapeHtml(__('Attach to Proposal Email')) ?></th>
                <th><?php echo $block->escapeHtml(__('Show in Frontend')) ?></th>
                <th><?php echo $block->escapeHtml(__('Action')) ?></th>
            </tr>
            <?php foreach ($uploadedFiles as $file) : ?>
                <?php $checkedCustomer = $block->isChecked($file, \Cart2Quote\Quotation\Model\Quote\File::CUSTOMER_FOLDER) ? 'checked="checked"' : '' ?>
                <?php $checkedEmail = $block->isChecked($file, \Cart2Quote\Quotation\Model\Quote\File::EMAIL_FOLDER) ? 'checked="checked"' : '' ?>
                <tr>
                    <td>
                        <a href="<?php echo $block->getDownloadUrl($file) ?>" class="file-name"><?php echo $block->trimFileName($file) ?></a>
                    </td>
                    <td>
                        <input type="hidden" <?php echo sprintf('name="upload_email[%s]"', $block->getCheckboxId($file)) ?> value="dont_email">
                        <input type="checkbox" <?php echo sprintf('name="upload_email[%s]"', $block->getCheckboxId($file)) ?> value="show_email" <?php echo $checkedEmail ?>>
                    </td>
                    <td>
                        <input type="hidden" <?php echo sprintf('name="upload_customer[%s]"', $block->getCheckboxId($file)) ?> value="dont_show">
                        <input type="checkbox" <?php echo sprintf('name="upload_customer[%s]"', $block->getCheckboxId($file)) ?> value="show_customer" <?php echo $checkedCustomer ?>>
                    </td>
                    <td>
                        <a href="#"  class="remove-file" onclick="removeFile('<?php echo $block->getDeleteUrl($file) ?>')"><i class="icon-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
    </table>
</form>
