<?php
$source = $block->getSource();
$order = $block->getOrder();
?>

<?php if ($source->getCreditlineTotalRefunded() > 0): ?>
    <tr>
        <td <?= $block->getLabelProperties() ?>>
            <?= __('Refunded to Credit Line'); ?>
        </td>
        <td <?= $block->getValueProperties() ?>><?= $order->formatPrice($source->getCreditlineTotalRefunded() - $source->getCreditlineRefunded()) ?></td>
    </tr>
    <tr>
        <td <?= $block->getLabelProperties() ?>>
            <?= __('Total Refunded to Credit Line'); ?>
        </td>
        <td <?= $block->getValueProperties() ?>><?= $order->formatPrice($source->getCreditlineTotalRefunded()) ?></td>
    </tr>
<?php endif ?>
