<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
/* avoid conflict  */
?>

<?php
$logFile='/var/log/relatednew.log';
    $writer = new \Zend\Log\Writer\Stream(BP . $logFile);
    $logger = new \Zend\Log\Logger();
    $logger->addWriter($writer);

use Magento\Framework\App\Action\Action;
/* @var WeltPixel\OwlCarouselSlider\Helper\Products $helper */
$helper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Products');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$urlVariable = $objectManager->create('Dcw\Products\Block\Desrdata');
$sliderConfiguration = $helper->getSliderConfiguration($block->getType());
$sliderConfig = json_encode($sliderConfiguration);
$helperCustom = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Custom');
$breakpointConfiguration = $helperCustom->getBreakpointConfiguration();
$displaySocial = $helperCustom->getDisplaySocial();
$breakpoint   = $breakpointConfiguration;
$enableSlider = (array_key_exists('status', $sliderConfiguration) && $sliderConfiguration['status'] == 1) ? true : false ;
$imageCreationOptions = [];
if ($enableSlider) {
    $imageCreationOptions['weltpixel_owlcarousel'] = true;
    if ($sliderConfiguration['lazyLoad']) {
        $imageCreationOptions['weltpixel_lazyLoad'] = true;
    }
}
$slideBy = 1;
?>
<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();
            $slideBy = $sliderConfiguration['slide_by'];
            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;
    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();
            $slideBy = $sliderConfiguration['slide_by'];
            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;
            $image = 'upsell_products_list';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $slideBy = $sliderConfiguration['slide_by'];
            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;
            $image = 'upsell_products_list';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $slideBy = $sliderConfiguration['slide_by'];
            $shuffle = 0;

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;
            $image = 'cart_cross_sell_products';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('More Choices:');
            $items = $block->getItemCollection();
            $slideBy = $sliderConfiguration['slide_by'];

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;
            $image = 'cart_cross_sell_products';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('More Choices:');
            $items = $block->getItems();
            $slideBy = $sliderConfiguration['slide_by'];

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;
            $image = 'new_products_content_widget_grid';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('New Products');
            $items = $exist;
            $slideBy = $sliderConfiguration['slide_by'];

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
?>

<?php if ($exist) {?>

<?php if ($type == 'related' || $type == 'upsell') { ?>
<?php if ($type == 'related'){ ?>
<div class="block-margin block <?php /* @escapeNotVerified */ echo $class . !$enableSlider ? ' row' : ''; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
    <?php } else { ?>
    <div class="block-margin block <?php /* @escapeNotVerified */ echo $class . !$enableSlider ? ' row' : ''; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php } ?>
        <?php } else { ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
            <?php } ?>
            <h3 class="block-title title">
                <span id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></span>
            </h3>
            <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart){ ?>
                    <!-- <div class="block-actions">
                        <?php /* @escapeNotVerified */ //echo __('Check items to add to the cart or') ?>
                        <button type="button" class="action select" data-role="select-all" role="select-all"><span><?php /* @escapeNotVerified */ //echo __('select all') ?></span></button>
                    </div> -->
                <?php } 

            ?>
                <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
                    <ol class="products list items product-items<?php echo $enableSlider ? ' owl-carousel-products-' . $type : ''; ?>">
                        <?php $product_item = $enableSlider ? '' : ' product-item'; ?>
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): 
                            $modelNo = $_item->getData('model_no');
                            ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'){ ?>
                                <?php if (!$_item->getRequiredOptions()){ ?>
                                    <?php $available = 'related-available'; ?>
                                <?php } ?>
                            <?php } ?>

                            <?php if ($type == 'related' || $type == 'upsell'){ ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="">' : '</li><li class="item product product-item" style="">' ?>
                            <?php } else { ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <?php } ?>
                            <?php
                            $productId = $_item->getId();
                            $stockItem = $objectManager->get('\Magento\CatalogInventory\Model\Stock\StockItemRepository');
                            $productStock = $stockItem->get($productId);
                            $stockStatus = $productStock['is_in_stock']; ?>

                            <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                                <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                <div class="product photo product-item-photo">
                                    <?php echo $block->getImage($_item, $image, $imageCreationOptions)->toHtml(); ?>
                                </div>
                                <div>
                                    <a href="#"
                                        data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                    </a>
                                                </div>
                                <div class="product details product-item-details">


                                    <strong class="product name product-item-name">
                                        <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>

                                        </a>
                                    </strong>
                                    <div class="sku-model-brand">
                                        <span class="smd"><?php echo "<label>Sku:</label>" . "<i class='smd-val'>".$_item->getData('sku')."</i>"; ?></span>
                                        <span class="smd"><?php echo "<label>Brand:</label>" ."<i class='smd-val'>" .$_item->getResource()->getAttribute('brand')->getFrontend()->getValue($_item)."</i>"; ?></span>
                                        <?php if($modelNo) { ?>
                                         <span class="smd-mod-wdt-lst"><?php echo "<label>Model:</label>"."<i class='smd-val-mod-val-lst'>". $_item->getData('model_no')."</i>"; ?></span>
                                       <?php } ?>
                                     </div>

                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>

                                <?php if( $_item->getData('type_id') == 'configurable' || $stockStatus == 0 ){ ?>
                               
                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                                            <div class="action-buttons config-action-btn">
                                             <button class="action tocart primary">
                                                 <a href="<?php echo $_item->getProductUrl() ?>" title="Add to Cart" class="action tab-addtocart add-to-cart">
                                                   <span>View Details</span>
                                                </a>
                                             </button>
                                             <button class="action primary toquote tocart quote-btn-list">
                                                 <a href="<?php echo $_item->getProductUrl() ?>" title="Request to Quote">
                                                   <span>Request Quote</span>
                                                </a>
                                             </button>
                                          </div>
                             
                                 <?php } ?>

                                <?php if ($templateType){ ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php } ?>

                                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'){ ?>
                                    <?php //if (!$_item->getRequiredOptions()){ ?>
                                        <?php $addToCart = $objectManager->create('Dcw\FeaturedProducts\Block\FeaturedProducts');
$postParams = $addToCart->getAddToCartPostParams($_item);
?>
                                        <form class="qty-block" data-role="tocart-form"
                                data-quote-submit-action="<?php echo $quoteUrl= $urlVariable->getAddToQuoteUrl($_item) ?>"
                                action="<?= $block->escapeUrl($postParams['action']) ?>"
                                method="post">
                                <?php echo $block->getBlockHtml('formkey') ?>
                                            <div class="control">
                                              <span class="input-group__addon">
                                                <span onclick="decreaseQtyRelated(<?= $block->escapeHtml($_item->getId()) ?>)" class="input-groupbutton input-group_button--decrease">
                                                  <span class="input-group_icon input-group_icon--decrease">-</span>
                                                </span>
                                              </span>
                                              <?php $logger->info("before"); ?>
                                               <input type="number" name="qty" onchange="changeQtyRelated(<?= $block->escapeHtml($_item->getId()) ?>)"id="qty-related-<?= $block->escapeHtml($_item->getId()) ?>" maxlength="5" class="input-group_input qty" value="1"/>
                                                 <span class="input-group__addon">
                                                   <span onclick="increaseQtyRelated(<?= $block->escapeHtml($_item->getId()) ?>)" class="input-groupbutton input-group_button--increase">
                                                    <span class="input-group_icon input-group_icon--increase">+</span>
                                                   </span>
                                                 </span>
                                            </div>
                                           <?php $logger->info("after"); ?>
                                         <?php /* @escapeNotVerified */ //echo $block->getProductPrice($_item); ?>
                                        <div class="field choice related">
                                           <div class="field choice related">

                                           <?php if( $_item->getData('type_id') == 'simple' ){ ?>
                                                <div class="price-boxes">
                                                 <div class="home-product-price">
                                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                                         </div>
                                    
                                <?php 
                                $helperCustomPrice = $this->helper('Dcw\CustomPricing\Helper\Data');
                                $discounValues = $helperCustomPrice->getPercentageCalculation($_item);
                                if ($discounValues != '') {
                                $expeditedDiscountPercentage = $discounValues['discount_percentage'];

                                ?>
                                
                                     <div class="expedicted-price-discount">
                                <?php
                                $priceHelper = $objectManager->create('Magento\Framework\Pricing\PriceCurrencyInterface'); 
                                 if ($_item->getSpecialPrice()) {
                                   $customPrice = $_item->getSpecialPrice();
                                } else {
                                    $customPrice = $_item->getFinalPrice();
                                }
                                $price = $customPrice - (($customPrice/100)*$expeditedDiscountPercentage);
                                $formattedPrice = $priceHelper->convertAndFormat($price); 
                                $formattedPrice = $priceHelper->round($price); 
                                $formattedPrice = $priceHelper->getCurrencySymbol(); 

                                $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
                                $rate = $priceHelper->convert($price, 1, $currencyCode);
                                $customprice = round($rate,2);
                                $customprice = number_format((float)$customprice, 2, '.', '');
                                $customprice = number_format($customprice,2); 
                               echo $formattedPrice.$customprice;
                                ?>
                                <input type="hidden" name="delivery_options" class="delivery_options" value="<?php echo $rate;?>">
                            </div>
                            <?php } ?>
                                     </div>     
                                                                        
                                          <div class="action-buttons">
                                           <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <?php //$addToCart = $objectManager->create('Dcw\FeaturedProducts\Block\FeaturedProducts');
//$postParams = $addToCart->getAddToCartPostParams($_item);
 ?>
                     <input type="hidden" name="product" value="<?php echo $_item->getId() ?>">
                      <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                      <?php echo $block->getBlockHtml('formkey')?>

                        <button type="submit"
                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                class="action tocart primary">
                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                        </button>
                        <button type="submit"
                                data-role="addToQuoteButton"
                                title="<?php echo $block->escapeHtml(__('Request Quote')) ?>"
                                class="action primary toquote tocart quote-btn-list">
                                <span>
                        <?php echo $block->escapeHtml(__('Request Quote')) ?>
                                                </span>
                                            </button>
                                           </div>
                                            
                                             <?php } ?>

                                        </div>
                                        </div>
                                   </form>
                                    <?php //} ?>
                                <?php } ?>
                                <?php if ($showWishlist || $showCompare || $showCart){ ?>
                                    <div class="product actions product-item-actions">
                                        <?php if ($showCart){ ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()){ ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)){ ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php } else { ?>
                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php } ?>
                                                <?php } else { ?>
                                                    <?php if ($_item->getIsSalable()){ ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php } else { ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('View Details') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('View Details') ?></span>
                                                </button>
                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Request Quote') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Request Quote') ?></span>
                                                </button>
                                                    <?php } ?>
                                                <?php } ?>
                                            </div>
                                        <?php } ?>

                                            <?php if ($showWishlist || $showCompare){ ?>
                                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist){ ?>
                                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php } ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare) { ?>
                                                        <?php
                                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                        ?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                           data-role="add-to-links"
                                                           title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php } ?>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                            <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                    <?php if($enableSlider) { ?>
                    <div id="pre-div">
                        <?php $loaderHelper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\ImageLoader'); ?>
                        <?php if ($loaderHelper->useDefaultLoader() ) { ?>
                        <div class="cssload-loader">
                            <div class="cssload-inner cssload-one"></div>
                            <div class="cssload-inner cssload-two"></div>
                            <div class="cssload-inner cssload-three"></div>
                        </div>
                        <?php } else {  ?>
                            <table class="imageloader-loader">
                                <tbody>
                                    <tr>
                                        <td>
                                            <img src="<?= $loaderHelper->getLoadingImageUrl() ?>" />
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        <?php } ?>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <?php }?>

    <?php if($enableSlider) { ?>
    <script>
        require(['jquery', 'owl_carousel', 'owl_config' ],
            function ($) {
                $(document).ready(function() {
                    var products_type = '<?php echo $type;?>',
                        slider_config = <?php echo $sliderConfig; ?>,

                        carouselElement = $('.owl-carousel-products-' + products_type),

                        windowWidth = $(window).width(),
                        carouselWidth = carouselElement.width(),
                        carouselContainer = carouselWidth + 120,

                        items = ((slider_config.items >= 0 && slider_config.items != null) ? slider_config.items : 2),

                        stagePadding = slider_config.stagePadding != '' ? parseInt(slider_config.stagePadding) : 0,

                        sPBrk_1 = slider_config.stagePadding_brk1 != '' ? parseInt(slider_config.stagePadding_brk1) : 0,
                        sPBrk_2 = slider_config.stagePadding_brk2 != '' ? parseInt(slider_config.stagePadding_brk2) : 0,
                        sPBrk_3 = slider_config.stagePadding_brk3 != '' ? parseInt(slider_config.stagePadding_brk3) : 0,
                        sPBrk_4 = slider_config.stagePadding_brk4 != '' ? parseInt(slider_config.stagePadding_brk4) : 0;

                        /** Lazyload bug when fewer items exist in the carousel then the ones displayed */
                         carouselElement.on('initialized.owl.carousel', function(event){
                             var scopeSize = event.page.size,
                             navBtnL = carouselElement.find('.owl-prev'),
                             navBtnR = carouselElement.find('.owl-next');

                             if(event.item.count <= event.page.size) {
                                navBtnL.css('display', 'none');
                                navBtnR.css('display', 'none');
                            }

                             for (var i = 0; i < scopeSize; i++){
                                 var imgsrc = $(event.target).find('.owl-item').eq(i).find('img').attr('data-src');
                                 $(event.target).find('.owl-item').eq(i).find('img').attr('src', imgsrc);
                                 $(event.target).find('.owl-item').eq(i).find('img').attr('style', 'opacity: 1;');
                             }
                         });

                    carouselElement.owlCarousel({
                        nav                 :parseInt(slider_config.nav) == 1 ? true : false,
                        dots                :parseInt(slider_config.dots) == 1 ? true : false,
                        center              :parseInt(slider_config.center) == 1 ? true : false,
                        items               :items,
                        loop                :parseInt(slider_config.loop) == 1 ? true : false,
                        margin              :parseInt(slider_config.margin) != '' ? parseInt(slider_config.margin) : 0,
                        stagePadding        :parseInt(slider_config.center) == 1 ? 0 : stagePadding,
                        lazyLoad            :parseInt(slider_config.lazyLoad) == 1 ? true : false,
                        autoplay            :parseInt(slider_config.autoplay) == 1 ? true : false,
                        autoplayTimeout     :(slider_config.autoplayTimeout > 0 && slider_config.autoplayTimeout != null) ? parseInt(slider_config.autoplayTimeout) : 3000,
                        autoplayHoverPause  :parseInt(slider_config.autoplayHoverPause) == 1 ? true : false,
                        autoHeight          :false,
                        slideBy             :'<?php echo $slideBy ?>',


                        responsive:{
                            <?php echo $breakpoint['breakpoint_1']; ?>:{
                                nav             :parseInt(slider_config.nav_brk1) == 1 ? true : false,
                                dots            :parseInt(slider_config.dots_brk1) == 1 ? true : false,
                                items           :(slider_config.items_brk1  >= 0 && slider_config.items_brk1 != null) ? parseInt(slider_config.items_brk1) : items,
                                center          :parseInt(slider_config.center_brk1) == 1 ? true : false,
                                stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_1,
                            },
                            <?php echo $breakpoint['breakpoint_2']; ?>:{
                                nav             :parseInt(slider_config.nav_brk2) == 1 ? true : false,
                                dots            :parseInt(slider_config.dots_brk2) == 1 ? true : false,
                                items           :(slider_config.items_brk2  >= 0 && slider_config.items_brk2 != null) ? parseInt(slider_config.items_brk2) : items,
                                center          :parseInt(slider_config.center_brk2) == 1 ? true : false,
                                stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_2,
                            },
                            <?php echo $breakpoint['breakpoint_3']; ?>:{
                                nav             :parseInt(slider_config.nav_brk3) == 1 ? true : false,
                                dots            :parseInt(slider_config.dots_brk3) == 1 ? true : false,
                                items           :(slider_config.items_brk3  >= 0 && slider_config.items_brk3 != null) ? parseInt(slider_config.items_brk3) : items,
                                center          :parseInt(slider_config.center_brk3) == 1 ? true : false,
                                stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_3,
                            },
                            <?php echo $breakpoint['breakpoint_4']; ?>:{
                                nav             :parseInt(slider_config.nav_brk4) == 1 ? true : false,
                                dots            :parseInt(slider_config.dots_brk4) == 1 ? true : false,
                                items           :(slider_config.items_brk4  >= 0 && slider_config.items_brk4 != null) ? parseInt(slider_config.items_brk4) : items,
                                center          :parseInt(slider_config.center_brk4) == 1 ? true : false,
                                stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_4,
                            }
                        }
                    });

                    var carouselControls = carouselElement.find('.owl-nav');
                    if (carouselContainer >= windowWidth) {
                        carouselControls.find('.owl-prev').css({
                            'left': 0,
                            'top': -15
                        });
                        carouselControls.find('.owl-next').css({
                            'right': 0,
                            'top': -15
                        });
                    }

                    carouselElement.on('initialized.owl.carousel', function(event){
                         navBtnL = carouselElement.find('.owl-prev'),
                         navBtnR = carouselElement.find('.owl-next');

                         if(event.item.count <= event.page.size) {
                            navBtnL.css('display', 'none');
                            navBtnR.css('display', 'none');
                        }
                    });
                });
            });
    </script>
    <?php }?>
    <script>
        function decreaseQtyRelated(dataId){
                var qty = jQuery('#qty-related-'+dataId).val();
                qty = parseInt(qty) -1;
                if(qty < 1){
                    qty =1;
                }
                jQuery('#qty-related-'+dataId).val(qty);
                jQuery('#qtydata-'+dataId).val(qty);
                console.log("ttttttttt");
                return false;
                console.log(qty);
            }
            function increaseQtyRelated(dataId){
                var qty = jQuery('#qty-related-'+dataId).val();
                qty = parseInt(qty) +1;
                jQuery('#qty-related-'+dataId).val(qty);
                jQuery('#qtydata-'+dataId).val(qty);
                return false;
            }
            function changeQtyRelated(dataId){
                var qty = jQuery('#qty-related-'+dataId).val();
                if(qty< 1){
                    qty = 1;
                }
                jQuery('#qty-related-'+dataId).val(qty);
                jQuery('#qtydata-'+dataId).val(qty);
                return false;
            }
        </script>
<script type="text/x-magento-init">
 {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "addToQuoteButtonSelector": "[data-role=addToQuoteButton]",
                "addToCartButtonSelector": "[data-role=addToCartButton]"
            }
        }
    }
    </script>

<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        $('.expedicted-price-discount').parents('.price-boxes').addClass('active');
    });
</script>
<style type="text/css">
  .price-boxes.active .home-product-price{display:none}
</style>