<?php
/**
 * Copyright (c) 2021. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 * @codingStandardsIgnoreFile
 */


?>
<section class="admin__page-section edit-quote-comments">
    <ul class="note-list">
        <?php foreach ($block->getFullHistory() as $_item) : ?>
            <li class="note-list-item">
                <span class="note-list-date"><?php echo $block->escapeHtml($block->getItemCreatedAt($_item)) ?></span>
                <span class="note-list-time"><?php echo $block->escapeHtml($block->getItemCreatedAt($_item, 'time')) ?></span>
                <span class="note-list-status"><?php echo $block->escapeHtml($block->getItemTitle($_item)) ?></span>
                <?php if ($block->isItemNotified($_item, false)) : ?>
                    <span class="note-list-customer">
                    <?php echo $block->escapeHtml(__('Customer')) ?>
                        <?php if ($block->isCustomerNotificationNotApplicable($_item)) : ?>
                            <span
                                    class="note-list-customer-notapplicable"
                            ><?php echo $block->escapeHtml(__('Notification Not Applicable')) ?></span>
                        <?php elseif ($block->isItemNotified($_item)) : ?>
                            <span class="note-list-customer-notified"><?php echo $block->escapeHtml(__('Notified')) ?></span>
                        <?php else : ?>
                            <span class="note-list-customer-not-notified"><?php echo $block->escapeHtml(__('Not Notified')) ?></span>
                        <?php endif; ?>
                </span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="edit-quote-comments-block">
        <div class="edit-quote-comments-block-title">
            <?php echo $block->escapeHtml(__('Notes for this Quote')) ?>
        </div>
        <?php foreach ($block->getFullHistory() as $_item) : ?>
            <?php if ($_comment = $block->getItemComment($_item)) : ?>
                <div class="comments-block-item">
                    <div class="comments-block-item-comment">
                        <?php echo $block->escapeHtml($_comment) ?>
                    </div>
                    <span class="comments-block-item-date-time">
                        <?php echo $block->escapeHtml(__('Comment added')) ?>
                        <?php echo $block->escapeHtml($block->getItemCreatedAt($_item)) ?>
                        <?php echo $block->escapeHtml($block->getItemCreatedAt($_item, 'time')) ?>
                    </span>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</section>
