<?php
/*
 * Copyright (c) 2021. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Cart2Quote\Quotation\Block\Quote\Files $block */ ?>

<?php $uploadedFiles = $block->getFiles(); ?>
<div class="order-details-items file-uploads">
    <table>
        <thead id="file-upload">
        <?php if (is_array($uploadedFiles)) : ?>
            <tr class="table-heading">
                <th>
                    <label class="field-label" for="uploaded_files">
                        <?php echo $block->escapeHtml(__('Uploaded Files:')) ?>
                    </label>
                </th>
                <td class="uploaded-files">
                    <ul>
                        <?php foreach ($uploadedFiles as $file) : ?>
                            <li>
                                <a href="<?php echo $block->getDownloadUrl($file) ?>"><?php echo $block->trimFileName($file) ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </td>
            </tr>
        <?php else : ?>
            <tr>
                <th>
                    <label class="field-label" for="uploaded_files">
                        <?php echo $block->escapeHtml(__('No Files uploaded')) ?>
                    </label>
                </th>
            </tr>
        <?php endif; ?>
        </thead>
    </table>
</div>

