<?php
/**
 * Copyright (c) 2021. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\DefaultRenderer $block */

$itemBaseCost = $block->getItemBaseCost($block->getItem());
$itemCost = $block->getItemCost($block->getItem());
?>
<div class="tier-item">
    <div class="tier-item-cost-price">
        <?php if ($block->getQuote()->isCurrencyDifferent()) : ?>
            <div class="price">
                <?php echo $block->getQuote()->formatBasePricePrecision(
                    $itemBaseCost,
                    2
                ) ?>
            </div>
            <br/>
        <?php endif; ?>
        <?php $name = 'item[' . $block->escapeHtml($block->getItemId()) . '][tier_item][%template%][%increment%][base_cost]'; ?>
        <input name="<?php echo $name; ?>"
               value="<?php echo sprintf('%.2f', $itemCost)?>"
               class="input-text item-price admin__control-text"
        />
    </div>
</div>
