<?php
/**
 * Copyright (c) 2019
 * Copyright Holder : CompactCode - CompactCode BvBa - Belgium
 * Copyright : Unless granted permission from CompactCode BvBa.
 * You can not distribute, reuse, edit, resell or sell this.
 */

/**
 * @var $block \Magento\Backend\Block\Template
 */
$itemid = $block->getRequest()->getParam('id');
?>

<?php if (isset($itemid)) : ?>
    <?= $block->getChildHtml() ?>
<?php endif; ?>
