<?php
namespace Dcw\CreditForm\Setup;
use Magento\Framework\Setup\SchemaSetupInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\DB\Ddl\Table;
class InstallSchema implements \Magento\Framework\Setup\InstallSchemaInterface{
    public function install(SchemaSetupInterface $setup,ModuleContextInterface $context){
        $setup->startSetup();
        $conn = $setup->getConnection();
        $tableName = $setup->getTable('creditform');
        if($conn->isTableExists($tableName) != true){
            $table = $conn->newTable($tableName)
                            ->addColumn(
                                'id',
                                Table::TYPE_INTEGER,
                                null,
                     ['identity'=>true,'unsigned'=>true,'nullable'=>false,'primary'=>true]
                                )
                            ->addColumn(
                                'status',
                                Table::TYPE_TEXT,
                                255,
                                ['nullable'=>false,'default'=>'']
                                )
                            ->addColumn(
                                'customer_email',
                                Table::TYPE_TEXT,
                                255,
                                ['nullable'=>false,'default'=>'']
                                )
                            ->addColumn(
                                'name',
                                Table::TYPE_TEXT,
                                255,
                                ['nullable'=>false,'default'=>'']
                                )
                            ->addColumn(
                                'title',
                                 Table::TYPE_TEXT,
                                 255,
                                 ['nullable'=>false,'default'=>'']
                                 )
                            ->addColumn(
                                'company',
                                Table::TYPE_TEXT,
                                 555,
                                ['nullable'=>false,'default'=>'']
                                )
                            ->addColumn(
                                'phone',
                                Table::TYPE_TEXT,
                                255,
                                ['nullable'=>false,'default'=>'']
                                )
                            ->addColumn(
                                'fax',
                                Table::TYPE_TEXT,
                                255,
                                ['nullable'=>false,'default'=>'']
                                )
                            ->addColumn(
                                'email',
                                Table::TYPE_TEXT,
                                '2M',
                                ['nullbale'=>false,'default'=>'']
                                )
                            ->addColumn(
                                 'company_address',
                                 Table::TYPE_TEXT,
                                 '2M',
                                 ['nullbale'=>false,'default'=>'']
                                 )
                            ->addColumn(
                                'city',
                                Table::TYPE_TEXT,
                                255,
                                ['nullbale'=>false,'default'=>'']
                                )
                            ->addColumn(
                                'state',
                                Table::TYPE_TEXT,
                                255,
                                ['nullbale'=>false,'default'=>'']
                                )
                            ->addColumn(
                                'country',
                                Table::TYPE_TEXT,
                                255,
                                ['nullbale'=>false,'default'=>'']
                                )
                            ->addColumn(
                                'postalcode',
                                Table::TYPE_TEXT,
                                255,
                                ['nullbale'=>false,'default'=>'']
                                )
                            ->addColumn(
                                'databusiness',
                                Table::TYPE_TEXT,
                                255,
                                ['nullbale'=>false,'default'=>'']
                                )
                            ->addColumn(
                                 'business_type',
                                 Table::TYPE_TEXT,
                                 255,
                                 ['nullbale'=>false,'default'=>'']
                                 )
                            ->addColumn(
                                'billing_address',
                                Table::TYPE_TEXT,
                                '2M',
                                ['nullbale'=>false,'default'=>'']
                                )
                                ->addColumn(
                                    'credit_city',
                                    Table::TYPE_TEXT,
                                    255,
                                    ['nullbale'=>false,'default'=>'']
                                    )
                                ->addColumn(
                                    'credit_state',
                                    Table::TYPE_TEXT,
                                    255,
                                    ['nullbale'=>false,'default'=>'']
                                    )
                                ->addColumn(
                                    'credit_country',
                                    Table::TYPE_TEXT,
                                    255,
                                    ['nullbale'=>false,'default'=>'']
                                    )
                                    ->addColumn(
                                        'credit_postalcode',
                                        Table::TYPE_TEXT,
                                        255,
                                        ['nullbale'=>false,'default'=>'']
                                        )
                                    ->addColumn(
                                        'duns',
                                        Table::TYPE_TEXT,
                                        255,
                                        ['nullbale'=>false,'default'=>'']
                                        )
                                    ->addColumn(
                                         'tax',
                                         Table::TYPE_TEXT,
                                         255,
                                         ['nullbale'=>false,'default'=>'']
                                         )
                                    ->addColumn(
                                        'resale',
                                        Table::TYPE_TEXT,
                                        '2M',
                                        ['nullbale'=>false,'default'=>'']
                                        )
                                        ->addColumn(
                                            'address_confirmation',
                                            Table::TYPE_TEXT,
                                            '2M',
                                            ['nullable'=>false,'default'=>'']
                                            )
                                        ->addColumn(
                                            'apcontact',
                                             Table::TYPE_TEXT,
                                             255,
                                             ['nullable'=>false,'default'=>'']
                                             )
                                        ->addColumn(
                                            'apphone',
                                            Table::TYPE_TEXT,
                                             555,
                                            ['nullable'=>false,'default'=>'']
                                            )
                                        ->addColumn(
                                            'apfax',
                                            Table::TYPE_TEXT,
                                            255,
                                            ['nullable'=>false,'default'=>'']
                                            )
                                        ->addColumn(
                                            'apemail',
                                            Table::TYPE_TEXT,
                                            '2M',
                                            ['nullable'=>false,'default'=>'']
                                            )
                                        ->addColumn(
                                            'invoice',
                                            Table::TYPE_TEXT,
                                            1,
                                            ['nullbale'=>false,'default'=>'']
                                            )
                                        ->addColumn(
                                             'upload_file',
                                             Table::TYPE_TEXT,
                                             '2M',
                                             ['nullbale'=>false,'default'=>'']
                                             )
                                        ->addColumn(
                                            'terms_conditions',
                                            Table::TYPE_TEXT,
                                            255,
                                            ['nullbale'=>false,'default'=>'']
                                            )

                            ->setOption('charset','utf8');
            $conn->createTable($table);
        }
        $setup->endSetup();
    }
}
?>
