<?php
/**
 * Copyright (c) 2021. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 * @codingStandardsIgnoreFile
 */

/** @var \Cart2Quote\Quotation\Block\Quote\Item\Renderer\Column $block */

?>
<?php if ($block->isHidePrices()) : ?>
<td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
    <?php echo $block->getRowTotalHtml(); ?>
    <?php echo $block->getTierRowTotalHtml(); ?>
</td>
<?php endif; ?>
