<?php
/**
 * Copyright (c) 2021. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 * @codingStandardsIgnoreFile
 */

/** @var \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\DefaultRenderer $block */
?>
<?php if ($block->getIsSelectedTier()) : ?>
    <input name="item[<?php echo $block->escapeHtml($block->getItemId()) ?>][percentage_discount]"
           value="<?php echo $block->escapeHtml($block->getAppliedValue()) ?>" type="hidden"
    />
<?php endif; ?>
<input name="item[<?php echo $block->escapeHtml($block->getItemId()) ?>][tier_item][<?php echo $block->escapeHtml($block->getTierItem()->getId()) ?>][percentage_discount]"
       id="item[<?php echo $block->escapeHtml($block->getItemId()) ?>][tier_item][<?php echo $block->escapeHtml($block->getTierItem()->getId()) ?>][percentage_discount]"
       class="input-text admin__control-text quote-percentage-discount-box"
       value="<?php echo $block->escapeHtml($block->getAppliedValue()) ?>" type="number" style="width:80px"
       data-appliedPercentage="<?php echo $block->escapeHtml($block->getAppliedValue()) ?>"
/>
