<?php
/**
 * Copyright (c) 2021. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 * @codingStandardsIgnoreFile
 */

/** @var \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\Columns\PriceQuoted $block */
?>
<?php
$htmlName = 'tier_item';
$tierItemHtmlId = 'tier_item_custom_price_' . $block->getTierItem()->getId();

$baseCustomPrice = $block->getPriceWithCorrectTax($block->getTierItem()->getBaseCustomPrice());
$customPrice = $block->getPriceWithCorrectTax($block->getTierItem()->getCustomPrice());
$costPrice = $block->getCostPrice();
?>
<div class="tier-item">
    <div class="tier-item-price">
        <?php if ($block->getQuote()->isCurrencyDifferent()) : ?>
            <div class="price" data-mage-init='{"currency":{"inputSelector": "<?php echo $block->escapeHtml($tierItemHtmlId) ?>"}}'>
                <?php echo $block->getQuote()->formatBasePricePrecision(
                    $baseCustomPrice,
                    2
                ) ?>
            </div>
            <br/>
        <?php endif; ?>
        <?php $name = 'item[' . $block->escapeHtml($block->getItemId()) . '][tier_item][' . $block->escapeHtml($block->getTierItem()->getId()) . '][custom_price]'; ?>
        <input id="<?php echo $block->escapeHtml($tierItemHtmlId); ?>"
               name="<?php echo $block->escapeHtml($name); ?>"
               value="<?php echo $block->escapeHtml(sprintf('%.2f', $customPrice)) ?>"
               class="input-text item-price admin__control-text"
               data-costprice="<?php echo $block->escapeHtml($costPrice) ?>"
               data-value="<?php echo $block->escapeHtml(sprintf('%.2f', $customPrice)); ?>"
               data-mage-init='{"priceQuoted":{"discountElementSelector": "<?= sprintf('item[%s][tier_item][%s][percentage_discount]',  $block->escapeHtml($block->getItemId()), $block->escapeHtml($block->getTierItem()->getId())) ?>"}}'
        />
    </div>
</div>
