<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Contact\Block\ContactForm $block */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeInformation = $objectManager->create('Magento\Store\Model\Information');
$store = $objectManager->create('Magento\Store\Model\Store');
$storeInfo = $storeInformation->getStoreInformationObject($store); 
// if($order == 'flatrate_flatrate')
// {
// $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/store.log');
// $logger = new \Zend\Log\Logger();
// $logger->addWriter($writer);
// $logger->info('Store info');
// $logger->info(print_r($storeInfo->getData(), true));
?>

<div class="container cnct-from-page">
  
  <div class="row cnct-frm-page">
    <div class="col-md-6" style="height:431px;">
          <h1>Contact Us </h1>
      <form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" placeholder="Name*" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('name') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" placeholder="Email Address*" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" placeholder="Phone Number"value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>
        <div class="field comment required">
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" placeholder="Message*" data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar cnt-frm-btn">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Send Message')) ?></span>
            </button>
        </div>
    </div>
</form>
    </div>
    <div class="col-md-5 " style="background-color:#212858; border-radius:8px; height:431px;">
      <div class="company-address-info">
<?php
$name =  $storeInfo->getName();
$city =$storeInfo->getCity();
$region =$storeInfo->getRegion();
$postcode =$storeInfo->getPostcode();
$countryId =$storeInfo->getCountryId();?>
<?php $phone = $storeInfo->getPhone(); 
$countryId = $storeInfo->getcountryId(); //echo "countryid"; echo $countryId;
$regionDat = $objectManager->create('Magento\Directory\Model\ResourceModel\Region\Collection'); 
$regionData = $regionDat->addRegionNameFilter($region)
            ->getFirstItem()
            ->toArray();
$regionCode = $regionData['code']; ?></p>
<p class="co-addr">
<?php echo $name ."<br>".$storeInfo['street_line1']."<br>".$city.", " .$regionCode." ".$postcode; ?>
</p>

<label class="label1 cnct-frm-labl"><span><?= $block->escapeHtml(__('Toll Free:')) ?></span>
<span><?= $block->escapeHtml(__('(877) 280-7278')) ?></span></label>

<label class="label2 cnct-frm-labl"><span><?= $block->escapeHtml(__('Phone:')) ?></span>
<span><?= $block->escapeHtml(__('(909) 923-8333')) ?></span></label> 

<label class="label3 cnct-frm-labl"><span><?= $block->escapeHtml(__('Fax:')) ?></span>
<span><?= $block->escapeHtml(__('(909) 944-2206')) ?></span></label>
</div>
    </div>
  </div>
</div>

<div class="col-md-1">

 </div>   