<?php
/**
 * Copyright (c) 2021. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 * @codingStandardsIgnoreFile
 */

/** @var \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\Columns\QuoteMargin $block */
?>
<strong>
    <?php if ($block->getEveryItemHasCost()) : ?>
        <?php echo __(
            '%1%',
            $block->getTotalMargin(
                $block->getQuote()->getCustomPriceTotal(),
                $block->getCostTotal()
            )
        ); ?>
    <?php else : ?>
        <?php echo __('N/A'); ?>
    <?php endif; ?>
</strong>
