<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="block block-dashboard-addresses">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Address Book')) ?></strong>
        <a class="action edit" href="<?= $block->escapeUrl($block->getAddressBookUrl()) ?>"><span><?= $block->escapeHtml(__('Manage Addresses')) ?></span></a>
    </div>
    <div class="block-content">
        <div class="box box-billing-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryBillingAddressHtml() ?>
                </address>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>" data-ui-id="default-billing-edit-link"><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
            </div>
        </div>
        <div class="box box-shipping-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryShippingAddressHtml() ?>
                </address>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>" data-ui-id="default-shipping-edit-link"><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<div class="custom-att-display">
  <?php
     $objm = \Magento\Framework\App\ObjectManager::getInstance();
     $customerSession = $objm->get('Magento\Customer\Model\Session');
     $filepath = $objm->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
     if($customerSession->isLoggedIn())
     {
          $pdfFilePath = $customerSession->getCustomer()->getUploadfile();
          $pdfFilePathArray = explode (",", $pdfFilePath);
          foreach($pdfFilePathArray as $pdfpath){
              $pdfFileNames = explode ("/", $pdfpath);
              $name = end($pdfFileNames);
              if(!$name)
                  continue;
              ?>
            <div class = "uploaded-file">
              <a href="<?php echo $filepath.$pdfpath; ?>" target="_blank"><?php echo $name; ?> </a><br>
            </div>
          <?php }
     }
     //  $customerinfo = $block->getCustomer();//print_r($customerinfo); ?>
</div>
<script type="text/javascript">
  require([
        'Magento_Customer/js/customer-data'
    ], function (customerData) {
      //console.log('Test');
        var sections = ['cart'];
        customerData.invalidate(sections);
        customerData.reload(sections, true);
    });
</script>
