<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$modellabel = $_product->getResource()->getAttribute('model_no')->getFrontend()->getLabel($_product);
$modelNo = $_product->getModelNo();
/*print_r($modellabel);
print_r("ffffffffff");
print_r($modelNo);*/

$prefix = ($_code && $_code == 'sku') ? ' #: ' : '';
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue) :?>
<div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
    <?php if ($renderLabel) :?>
        <!-- <strong class="type"><?= $block->escapeHtml($_attributeLabel.' #:') ?></strong> -->
        <strong class="type"><?= $block->escapeHtml($_attributeLabel) ?><?= /* @escapeNotVerified */ $prefix ?></strong>
    <?php endif; ?>
    <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>>
        <?= /* @noEscape */ $_attributeValue ?>
        </div>
        <?php if ($modelNo) :?>
             <span class="model"><?php 
               echo $modelNo;
                
             ?></span>
           <div class="pdp-mod-sku-val"> 
            <?php echo "Model #:"?>
             <span class="model"><?php 
               echo $modelNo;
                
             ?></span>
        </div>
        <?php endif; ?>
</div>
<?php endif; ?>

<style type="text/css">
    .model{display: none;}
    .pdp-mod-sku-val .model{display: inline-block;}
    span.model:empty + .pdp-mod-sku-val{display:none;}
</style>
