<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$helperpath = $objectManager->create('Magento\Catalog\Helper\Data');
$path = $helperpath->getBreadcrumbPath();
unset($path['product']);
$catIDS = '';
foreach ($path as $name => $breadcrumb) {

    $label = $breadcrumb['label'];
    $query = "SELECT DISTINCT `entity_id` FROM `catalog_category_entity_varchar` WHERE `value` = '$label' and entity_id!=2";
    $result = $connection->fetchRow($query);
    $categoryIds[] = $result['entity_id'];
    $catIDS = implode(', ',$categoryIds);
}
?>
<?php $_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $_product = $block->getProduct();
$_productSku = $block->getProduct()->getData('sku');
$_productType = $block->getProduct()->getData('type_id');
//echo $_productType; exit;
// echo "<pre>";
// print_r(json_encode($_product->getData())); ?>
<?php $stockItem = $_product->getExtensionAttributes()->getStockItem(); ?>
<?php
$priceCurrencyObject = $objectManager->get('Magento\Framework\Pricing\PriceCurrencyInterface'); //instance of PriceCurrencyInterface
$store  = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currencyCode = $store->getStore()->getCurrentCurrencyCode();

//$store = $this->_storeManager->getStore()->getStoreId(); //get current store id if store id not get passed
$rate = $priceCurrencyObject->convert($_product->getFinalPrice(), 1, $currencyCode);
$rate = round($rate,2);
?>
<div class="product-add-form">
    <form data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
          action="<?= $block->escapeUrl($block->getSubmitUrl($_product)) ?>" method="post" name="addcartform"
          id="product_addtocart_form"<?php if ($_product->getOptions()) :?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?= (int)$_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="item"  value="<?= (int)$block->getRequest()->getParam('id') ?>" />
        <input type="hidden" name="custom_price" value="<?php echo $rate;?>" id="custom_price_cal"/>

        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top') ?>

        <?php if (!$block->hasOptions()) :?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else :?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1') :?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2') :?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif;?>

        <?= $block->getChildHtml('form_bottom') ?>
        <?php echo $block->getChildHtml('extrahint'); ?>

 <?php if ($_productSku != 'custom-request-form' && $_productType == 'simple'){?>
   <div class="downloads_section">
<?php
$blockObj= $block->getLayout()->createBlock('Amasty\ProductAttachment\Block\Product\AttachmentsTab');
?>
<?php if ($stockItem->getIsInStock()) : ?>
<?php if ($files = $blockObj->getAttachments()) : ?>
 <?php
     $currentProduct = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
     $currentProductId = $currentProduct->getId();
 ?>
   <div class="widget am-attachments am-attachments-<?= $block->escapeHtml($this->getWidgetType()); ?>">
       <select name="attachment" onchange="getUrlFun(this.value);" id="attachment" class="atc_file">
       <option value="">Downloads</option>
       <?php foreach ($files as $file) : ?>

               <?php if($catIDS){ ?>
                 <option value="<?= $this->getBaseUrl().'downloads?productId='.$currentProductId.'&attachment_name='.$block->escapeHtml($file->getLabel()).'&cat_ids='.$catIDS?>" class="am-filelink" target="_blank">
               <?php }else{ ?>
                 <option value="<?= $this->getBaseUrl().'downloads?productId='.$currentProductId.'&attachment_name='.$block->escapeHtml($file->getLabel())?>" class="am-filelink" target="_blank">
               <?php } ?>
                      <?= $block->escapeHtml($file->getLabel()); ?>
               </option>

       <?php endforeach; ?>
       </select>
   </div>
<?php endif; ?>
<?php endif; ?>

       <!-- <div class="addit"> -->
           <!-- AddThis Button BEGIN -->
           <?php if ($stockItem->getIsInStock()) { ?>
               <h3>Share Product</h3>
             <div class="addthis_toolbox addthis_default_style ">
               <a class="addthis_button_facebook"></a>
                 <a class="addthis_button_twitter"></a>
                 <a class="addthis_button_linkedin"></a>
                 <a class="addthis_button_email"></a>

             </div>

               <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5cdd82b5521e49e" async="async"></script>
        <?php   } ?>
    </div>
 <?php  } ?>

    </form>
</div>

<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($_product->getId()) ?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });
        priceBoxes.priceBox({'priceConfig': <?= /* @noEscape */ $block->getJsonConfig() ?>});
    });
</script>
<script>
    function getUrlFun(aurl){
        if(aurl != '') {
            window.open(aurl,'_blank');
        }

    }
</script>
<?php if($_productType == "simple") { ?>
<script type="text/javascript">
require(['jquery'], function ($) {
$(document).ready(function () {
    $('body').addClass('simple_Product');
  });
});
</script>
<?php } ?>
<?php
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
?>
<script type="text/javascript">
require(['jquery'], function ($) {
$(document).ready(function () {
    $('body').addClass('logged_in');
  });
});
</script>

<?php } ?>