<?php
$orderAttributeData = $block->getOrderAttributesData();
$orderId = $this->getRequest()->getParam('order_id');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('\Magento\Sales\Model\Order')
                           ->load($orderId);

$incrementId = $order->getIncrementId();

$sampleIncrementId = "INC".$incrementId;

$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
$resource=$objectManager->create('\Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection(\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION);

$sql = "SELECT * FROM `order_storedaccount_values` where increment_id='$sampleIncrementId'";
$orderData = $connection->fetchRow($sql);

// echo "<pre>";
// print_r($orderAttributeData);
// exit;

?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Additional Information') ?></span>
        <div class="actions"><?= $this->getOrderAttributeEditLink(); ?></div>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <?php if (!empty($orderAttributeData)) : ?>
                        <?php foreach ($orderAttributeData as $data) : ?>

                            <?php if($data['code']=='account_selection_pm' || $data['code']== 'guest_fedex_radio_selectionpm' || $data['code']=='existing_account_selection_pm' || $data['code']=='ups_save_for_future_usepm' || $data['code']=='existing_account_selection_pm' || $data['code']=='fedex_radio_selectionpm' || $data['code']=='fedex_save_for_future_usepm')
                                        continue;
                            ?>
                            <tr>
                                <th><?= $block->escapeHtml($data['label']); ?></th>
                                <td>
                                    <strong><?= $block->escapeHtml($data['value']); ?></strong>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else : ?>
                        <tr>
                            <th>&nbsp;</th>
                            <td><?= $block->escapeHtml(__('No attributes for this order')); ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if($orderData['ups_account_no']!=0){?>
                      <tr>
                          <th><?= "UPS Account No:" ?></th>
                          <td>
                              <strong><?= $orderData['ups_account_no']; ?></strong>
                          </td>
                      </tr>
                  <?php }else if($orderData['fedex_account_no']!=0){?>
                    <tr>
                        <th><?= "Fedex Account No:" ?></th>
                        <td>
                            <strong><?= $orderData['fedex_account_no']; ?></strong>
                        </td>
                    </tr>
                  <?php }?>
                </table>
            </div>
        </div>
    </div>
</section>
